// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl-Q18waq2vpt9BxdInHDLl6p5jE9YieE',
    appId: '1:830999458824:web:a080b4914a77e778bfcdbd',
    messagingSenderId: '830999458824',
    projectId: 'blog-app-ca39d',
    authDomain: 'blog-app-ca39d.firebaseapp.com',
    storageBucket: 'blog-app-ca39d.appspot.com',
    measurementId: 'G-ZYTDREPKP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG3ibenEzjZuQ37XwQt-TkGDtIaiHWLMA',
    appId: '1:830999458824:android:b547d7ef067561a3bfcdbd',
    messagingSenderId: '830999458824',
    projectId: 'blog-app-ca39d',
    storageBucket: 'blog-app-ca39d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLo7iWsByTCxYM3Rl9k1vuZKanNBaAll4',
    appId: '1:830999458824:ios:100854d3b3bca174bfcdbd',
    messagingSenderId: '830999458824',
    projectId: 'blog-app-ca39d',
    storageBucket: 'blog-app-ca39d.appspot.com',
    iosClientId: '830999458824-12gbnctl2dp0gmg2fdlihma3hri860k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLo7iWsByTCxYM3Rl9k1vuZKanNBaAll4',
    appId: '1:830999458824:ios:100854d3b3bca174bfcdbd',
    messagingSenderId: '830999458824',
    projectId: 'blog-app-ca39d',
    storageBucket: 'blog-app-ca39d.appspot.com',
    iosClientId: '830999458824-12gbnctl2dp0gmg2fdlihma3hri860k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogApp',
  );
}
